### ISSUE TITLE
Strict DigitalOcean firewall rules required on all assets

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/meta#132]
### Context

Recommended by a cyber security expert on our board.

### Requirements

* Lockdown Digital Ocean network environments with firewall rulesets that deny all traffic by default and only allow traffic we architect into the application
   * [DO docs on this](https://docs.digitalocean.com/products/networking/firewalls/)

### Docs

* Instructions in staff docs about how to request new routes
* Guidance about when to open up new routes, what we're using certain routes for

**Comment by josh-chamberlain** [comment]
Lockdown Digital Ocean network environments with firewall rulesets that deny all traffic by default and only allow traffic we architect into the application

**Comment by mbodeantor** [comment]
Digital Ocean applies firewall rules to droplets, which we don't have any running right now. Our API is hosted on their app platform, which is locked down by default. I don't even see how I would access the underlying infrastructure for that so we should be good for now. In the future if we end up needing any droplets, we will make sure to lock them down.
