### ISSUE TITLE
Data Dictionary Docs Update

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/meta#217]
### Context

Update the gitbook docs for required schema updates: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/413/activities/data-sources/data-dictionaries/data-sources-data-dictionary

### Requirements

* Add and remove columns from the data dictionary docs according to this issue: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/62#issuecomment-1741190369

**Comment by josh-chamberlain** [comment]
closed by https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/435/activities/data-sources/data-dictionaries/data-sources-data-dictionary/~/details
